using UnityEngine;
using UnityEngine.UI;

public class SurprizeSceneCtrl : MonoBehaviour {

    //texts
    [SerializeField] private Text text;
    [SerializeField] private Text title;

    //btns
    [SerializeField] private Text btnText1;//always correct answer
    [SerializeField] private Text btnText2;//always medium answer
    [SerializeField] private Text btnText3;//always wrong answer

    private enum States {scenario1, scenario2}
    private States state;

	// Use this for initialization
	void Start () {
        state = States.scenario1;
	}
	
	// Update is called once per frame
	void Update () {
	    if(state == States.scenario1)
        {
            Scenario1();
        }
        else if (state == States.scenario2)
        {
            Scenario2();
        }
    }

    public void Scenario1()
    {
        text.text = "Five years have passed since the establishment of your wind farm." +
                    " The power consumption of the village is lower than initially planned due to most of its residents left.\n" +
                    "What do you consider to be the most appropriate option from the list below?\n" +
                    "Remember that based on the selected option a negative or positive score is calculated respectively.";

        title.text = "Scenario 1";
        btnText2.text = "Turn off completely the excess of wind turbines";
        btnText1.text = "Keep the wind farm and sell the excess of power generated by connecting the wind farm with the main electricity grid/high voltage lines";
        btnText3.text = "Do nothing keep everything as it is";
    }

    public void Scenario2()
    {
        text.text = "In this scenario things had gone opposite. The power consumption of the village " +
                    "has been increased because of a large hotel resort establishement in the area.\nHow you will react?";

        title.text = "Scenario 2";
        btnText1.text = "Try to install more wind turbines in the same area";
        btnText2.text = "Keep the wind farm as is and install \na new wind farm(or even solar panels) in a new area";
        btnText3.text = "Do nothing keep everything as it is";
    }

    public void BtnClicked(float score)
    {
        if (state == States.scenario1)
        {
            state = States.scenario2;
            GameManager.instance.score += score;
        }
        else if(state == States.scenario2)
        {
            GameManager.instance.score += score;
            GameManager.instance.LoadLevel("EndScene");
        }

    }
}
